### ISSUE TITLE
Interested in a custom design for this?

### ISSUE THREAD

**Issue by corysimmons** [joequery/JSON-Selector-Generator#1]
Just something simple and nicer looking than what you have.

Cool tool.

**Comment by joequery** [comment]
That would be great!

**Comment by corysimmons** [comment]
Care if I put a small logo to my company on it? I could do the same for you.

**Comment by joequery** [comment]
No logo please :)

**Comment by corysimmons** [comment]
Then I'm not going to do the redesign.

The logo looks like this:

![](http://i.imgur.com/hPIsMTx.png)

**Comment by joequery** [comment]
Sorry to hear that. Thanks for the offer!

**Comment by samccone** [comment]
😪
