### ISSUE TITLE
jsonselector.com down?

### ISSUE THREAD

**Issue by d8ahazard** [joequery/JSON-Selector-Generator#2]
Hey there! I see your jsonselector site is down!

Not sure how much else it gets...but I use it a lot. So much, that I actually just went through the work of making a V2 version of the app that's all JS-based. 

Not sure what your intentions are with the domain, but wondering if you'd consider letting me buy it from you if you're done with the project? I've already got a server I use for hosting some other (non-profit) projects, so in my mind, I'd just throw my new code on my server and forward the new domain to it.

If not, I totally get it. Either way - you have no idea how much I've used this tool in the past, so kudos. :D

**Comment by d8ahazard** [comment]
You can see the new version here: 

https://d8ahazard.github.io/JsonSelectorV2/

**Comment by joequery** [comment]
Hi there!

Thank you so much for bringing this to my attention. My server was rebooted by my host and I didn't have my sites set up to automatically launch. Yikes.

Your version is superior, so it would benefit the web at large to have your version used. Nice work :+1: 

I appreciate your shoutout in the README. :) 

Email me, joseph@vertstudios.com, and we can discuss the domain transfer process.

I might hack on your version at some point :)
